function reset(){
	if(vol != 1){
		for(S in AllSounds){
			AllSounds[S].volume = 0;
		}
	}
	//------------------------ Dumbledore64.js ------------------//
	STATE = 0;
	//Pause menu
	preSTATE = 0;
	keytimer = 0;
	nu = 0;
	hs = 0;
	cd = 0;
	hptimer = 0;
	spell1 = "N/A";
	spell2 = "N/A";
	spell = "N/A";
	spell1pic = "N/A";
	spell2pic = "N/A";
	//Score
	score = 0;
	muliplier = 1;
	multtimer = 0;
	//colors
	colorNum = 1;
	// Environment
	planted = false;
	jungleAni = false;
	// Alpha
	Alpha = 1;
	ctx.globalAlpha = 1;
	//StateTimer: for staying in levels with no boss
	StateTimer = 0;
	//End of game pause
	deathTimer = -1;
	jungleIndex = 0;
	player.x = 400;
	player.y = 256;
	player.width = 32;
	player.height = 32;
	player.speed = 8;
	player.speed2 = 2;
	player.dirct = 0;
	player.hp = 3;
	player.maxhp = 3;
	player.power = 1;
	player.dmg = false;
	player.dir = "W";
	player.LR = "";
	castingBar.x = player.x - player.width/2;
	castingBar.y = player.y + player.height/2;
	castingBar.width = player.width;
	castingBar.height = player.height/4;
	castingBar.width2 = 0;
	castingBar.onScreen = 0;
	castingBar.cast = -1;
	castingBar.castmax = 0;
	TreecastingBar.x = player.x - player.width/2;
	TreecastingBar.y = player.y + player.height/2;
	TreecastingBar.width = player.width;
	TreecastingBar.height = player.height/4;
	TreecastingBar.width2 = 0;
	TreecastingBar.onScreen = 0;
	TreecastingBar.cast = -1;
	TreecastingBar.castmax = 0;
	
	for(M in markerlist){
		markerlist[M].color = "#00FF00";
		markerlist[M].speed = 4;
		markerlist[M].timeLeft = 0;
		markerlist[M].x = -100;
		markerlist[M].y = -100;
		markerlist[M].points = 0;
		markerlist[M].mult = 1;
	}
	for(M in typemarkerlist){
		typemarkerlist[M].color = "#00FF00";
		typemarkerlist[M].speed = 4;
		typemarkerlist[M].timeLeft = 0;
		typemarkerlist[M].x = -100;
		typemarkerlist[M].y = -100;
		typemarkerlist[M].text = "";
	}
	inits = {1: "_", 2: "_", 3: "_", 4: "_", 5: "_", 6: "_", 7: "_", 8: "_"};
	init = "_____";
	initsInd = 1;
	hsColor = 1;
	hsNum = 0;
	wait = 0;
	lowestScore = highscore5;
	for(S in AllSounds){
		AllSounds[S].currentTime = 0;
		AllSounds[S].pause;
	}
	
	//Remove _ in initials
	var chars = hs1init.split('');
	for(C in chars){
		if(chars[C] == "_"){
			chars[C] = " ";
		}
	}
	hs1init = chars[0] + chars[1] + chars[2] + chars[3] + chars[4] + chars[5] + chars[6] + chars[7];
	var chars = hs2init.split('');
	for(C in chars){
		if(chars[C] == "_"){
			chars[C] = " ";
		}
	}
	hs2init = chars[0] + chars[1] + chars[2] + chars[3] + chars[4] + chars[5] + chars[6] + chars[7];
	var chars = hs3init.split('');
	for(C in chars){
		if(chars[C] == "_"){
			chars[C] = " ";
		}
	}
	hs3init = chars[0] + chars[1] + chars[2] + chars[3] + chars[4] + chars[5] + chars[6] + chars[7];
	var chars = hs4init.split('');
	for(C in chars){
		if(chars[C] == "_"){
			chars[C] = " ";
		}
	}
	hs4init = chars[0] + chars[1] + chars[2] + chars[3] + chars[4] + chars[5] + chars[6] + chars[7];
	var chars = hs5init.split('');
	for(C in chars){
		if(chars[C] == "_"){
			chars[C] = " ";
		}
	}
	hs5init = chars[0] + chars[1] + chars[2] + chars[3] + chars[4] + chars[5] + chars[6] + chars[7];
	//------------------------ Environment.js -------------------//
	for(O in obstacle1){
		obstacle1[O].growTimer = Math.floor(Math.random() * 60);
	}
	for(O in ObsList){
		ObsList[O].width = 32;
		ObsList[O].height = 32;
		ObsList[O].hp = 3;
		ObsList[O].hptimer = 0;
		ObsList[O].index = 1;
	}
	//------------------------ Pickups.js -----------------------//
	for(E in allEleCubes){
		allEleCubes[E].type = 1;
		allEleCubes[E].x = -100;
		allEleCubes[E].y = -200;
		allEleCubes[E].width = 32;
		allEleCubes[E].height = 32;
		allEleCubes[E].timeLeft = 0;
		allEleCubes[E].index = 1;
		allEleCubes[E].stage = "up";
	}
	
	RandomCube.type = 1;
	RandomCube.x = -100;
	RandomCube.y = -200;
	RandomCube.width = 32;
	RandomCube.height = 32;
	RandomCube.timeLeft = 0;
	RandomCube.index = 1;
	RandomCube.stage = "up";
	
	RandEffect.color = "#FF00FF";
	RandEffect.width = 32;
	RandEffect.height = 32;
	RandEffect.x = -100;
	RandEffect.y = -200;
	RandEffect.onScreen = 0;
	RandEffect.frame = 0;
	RandEffect.used = 0;
	
	counter = 0;
	
	hpUp.type = 0;
	hpUp.x = -100;
	hpUp.y = -200;
	hpUp.width = 32;
	hpUp.height = 32;
	hpUp.boss = "treeW";
	
	hpParticleW.type = 0;
	hpParticleW.x = -100;
	hpParticleW.y = -200;
	hpParticleW.width = 32;
	hpParticleW.height = 32;
	hpParticleW.dir = "W";
	hpParticleW.speed = 8;
	hpParticleW.dirct = 30;
	hpParticleW.index = 1;
	
	hpParticleA.type = 0;
	hpParticleA.x = -100;
	hpParticleA.y = -200;
	hpParticleA.width = 32;
	hpParticleA.height = 32;
	hpParticleA.dir = "A";
	hpParticleA.speed = 8;
	hpParticleA.dirct = 30;
	hpParticleA.index = 2;
	
	hpParticleS.type = 0;
	hpParticleS.x = -100;
	hpParticleS.y = -200;
	hpParticleS.width = 32;
	hpParticleS.height = 32;
	hpParticleS.dir = "S";
	hpParticleS.speed = 8;
	hpParticleS.dirct = 30;
	hpParticleS.index = 3;
	
	hpParticleD.type = 0;
	hpParticleD.x = -100;
	hpParticleD.y = -200;
	hpParticleD.width = 32;
	hpParticleD.height = 32;
	hpParticleD.dir = "D";
	hpParticleD.speed = 8;
	hpParticleD.dirct = 30;
	hpParticleD.index = 4;
	
	hpParticleWA.type = 0;
	hpParticleWA.x = -100;
	hpParticleWA.y = -200;
	hpParticleWA.width = 32;
	hpParticleWA.height = 32;
	hpParticleWA.dir = "WA";
	hpParticleWA.speed = 8;
	hpParticleWA.dirct = 30;
	hpParticleWA.index = 5;
	
	hpParticleWD.type = 0;
	hpParticleWD.x = -100;
	hpParticleWD.y = -200;
	hpParticleWD.width = 32;
	hpParticleWD.height = 32;
	hpParticleWD.dir = "WD";
	hpParticleWD.speed = 8;
	hpParticleWD.dirct = 30;
	hpParticleWD.index = 6;
	
	hpParticleAS.type = 0;
	hpParticleAS.x = -100;
	hpParticleAS.y = -200;
	hpParticleAS.width = 32;
	hpParticleAS.height = 32;
	hpParticleAS.dir = "AS";
	hpParticleAS.speed = 8;
	hpParticleAS.dirct = 30;
	hpParticleAS.index = 7;
	
	hpParticleSD.type = 0;
	hpParticleSD.x = -100;
	hpParticleSD.y = -200;
	hpParticleSD.width = 32;
	hpParticleSD.height = 32;
	hpParticleSD.dir = "SD";
	hpParticleSD.speed = 8;
	hpParticleSD.speed2 = 4;
	hpParticleSD.dirct = 30;
	hpParticleSD.index = 8;
	//------------------------ Enemies.js -----------------------//
	Enemy.type = 0;
	Enemy.bug = 0;
	Enemy.onTree = 0;
	Enemy.x = 9000;
	Enemy.y = -400;
	Enemy.width = 32;
	Enemy.height = 32;
	Enemy.speed = 4;
	Enemy.speed2 = 2;
	Enemy.dirct = 0;
	Enemy.dir = "W";
	Enemy.respawn = 1;
	Enemy.rp = 100;
	Enemy.pts = 50;
	Enemy.LR = "";
	Enemy.onScreen = 0;
	Enemy.movement = false;
	
	EnemyA.type = 0;
	EnemyA.bug = 1;
	EnemyA.onTree = 0;
	EnemyA.x = -9000;
	EnemyA.y = -9000;
	EnemyA.width = 32;
	EnemyA.height = 32;
	EnemyA.speed = 4;
	EnemyA.speed2 = 2;
	EnemyA.dirct = 0;
	EnemyA.dir = "W";
	EnemyA.respawn = 250;
	EnemyA.rp = 100;
	EnemyA.pts = 50;
	EnemyA.LR = "";
	EnemyA.onScreen = 0;
	EnemyA.movement = false;
	EnemyA.index = 1;
	EnemyA.dindex = 1;
	
	EnemyB.type = 0;
	EnemyB.bug = 0;
	EnemyB.onTree = 0;
	EnemyB.x = -9000;
	EnemyB.y = -9000;
	EnemyB.width = 32;
	EnemyB.height = 32;
	EnemyB.speed = 4;
	EnemyB.speed2 = 2;
	EnemyB.dirct = 0;
	EnemyB.dir = "W";
	EnemyB.respawn = 125;
	EnemyB.rp = 100;
	EnemyB.pts = 50;
	EnemyB.LR = "";
	EnemyB.onScreen = 0;
	EnemyB.movement = false;
	
	EnemyC.type = 0;
	EnemyC.bug = 1;
	EnemyC.onTree = 0;
	EnemyC.x = -9000;
	EnemyC.y = -9000;
	EnemyC.width = 32;
	EnemyC.height = 32;
	EnemyC.speed = 4;
	EnemyC.speed2 = 2;
	EnemyC.dirct = 0;
	EnemyC.dir = "W";
	EnemyC.respawn = 300;
	EnemyC.rp = 100;
	EnemyC.pts = 50;
	EnemyC.LR = "";
	EnemyC.onScreen = 0;
	EnemyC.movement = false;
	EnemyC.index = 1;
	EnemyC.dindex = 1;
	
	Tenemy.type = 0;
	Tenemy.bug = 0;
	Tenemy.onTree = 0;
	Tenemy.x = 2000;
	Tenemy.y = 0;
	Tenemy.width = 32;
	Tenemy.height = 32;
	Tenemy.speed = 8;
	Tenemy.speed2 = 4;
	Tenemy.dirct = 0;
	Tenemy.dir = "W";
	Tenemy.respawn = 600;
	Tenemy.rp = 600;
	Tenemy.pts = 50;
	Tenemy.frame = 1;
	Tenemy.onScreen = 0;
	Tenemy.movement = false;
	
	TenemyA.type = 0;
	TenemyA.bug = 0;
	TenemyA.onTree = 0;
	TenemyA.x = 2000;
	TenemyA.y = 0;
	TenemyA.width = 32;
	TenemyA.height = 32;
	TenemyA.speed = 8;
	TenemyA.speed2 = 4;
	TenemyA.dirct = 0;
	TenemyA.dir = "W";
	TenemyA.respawn = 2400;
	TenemyA.rp = 600;
	TenemyA.pts = 50;
	TenemyA.frame = 1;
	TenemyA.onScreen = 0;
	TenemyA.movement = false;
	
	TenemyB.type = 0;
	TenemyB.bug = 0;
	TenemyB.onTree = 0;
	TenemyB.x = 2000;
	TenemyB.y = 0;
	TenemyB.width = 32;
	TenemyB.height = 32;
	TenemyB.speed = 8;
	TenemyB.speed2 = 4;
	TenemyB.dirct = 0;
	TenemyB.dir = "W";
	TenemyB.respawn = 1800;
	TenemyB.rp = 600;
	TenemyB.pts = 50;
	TenemyB.frame = 1;
	TenemyB.onScreen = 0;
	TenemyB.movement = false;
	
	for(L in lavamenlist){
		lavamenlist[L].type = 0;
		lavamenlist[L].bug = 0;
		lavamenlist[L].onTree = 0;
		lavamenlist[L].x = 9000;
		lavamenlist[L].y = -400;
		lavamenlist[L].width = 32;
		lavamenlist[L].height = 32;
		lavamenlist[L].speed = 4;
		lavamenlist[L].speed2 = 2;
		lavamenlist[L].dirct = 0;
		lavamenlist[L].dir = "W";
		lavamenlist[L].respawn = -1;
		lavamenlist[L].rp = -1;
		lavamenlist[L].pts = 50;
		lavamenlist[L].onScreen = 0;
		lavamenlist[L].movement = false;
	}
	
	Spawner.type = 2;
	Spawner.x = 2000;
	Spawner.y = 0;
	Spawner.onTree = 0;
	Spawner.width = 64;
	Spawner.height = 64;
	Spawner.speed = 2;
	Spawner.speed2 = 1;
	Spawner.dirct = 0;
	Spawner.hp = 5;
	Spawner.hptimer = 0;
	Spawner.respawn = 300;
	Spawner.dir = "W";
	Spawner.rp = 450;
	Spawner.pts = 500;
	Spawner.onScreen = 0;
	Spawner.cd = 60;
	Spawner.movement = false;
	
	Sorceror.type = 1;
	Sorceror.x = 2000;
	Sorceror.y = 0;
	Sorceror.onTree = 0;
	Sorceror.width = 32;
	Sorceror.height = 32;
	Sorceror.speed = 4;
	Sorceror.speed2 = 2;
	Sorceror.dirct = 0;
	Sorceror.hp = 3;
	Sorceror.spell = "Ice";
	Sorceror.hptimer = 0;
	Sorceror.respawn = 1200;
	Sorceror.dir = "W";
	Sorceror.rp = 1200;
	Sorceror.pts = 500;
	Sorceror.onScreen = 0;
	Sorceror.cd = 0;
	Sorceror.movement = false;
	Sorceror.spawned = 60;
	
	treeWizz.type = -1;
	treeWizz.x = 9000;
	treeWizz.onTree = 0;
	treeWizz.y = -400;
	treeWizz.width = 32;
	treeWizz.height = 32;
	treeWizz.speed = 4;
	treeWizz.speed2 = 2;
	treeWizz.dirct = 0;
	treeWizz.dir = "W";
	treeWizz.respawn = -1;
	treeWizz.rp = -1;
	treeWizz.onScreen = 0;
	treeWizz.movement = false;
	treeWizz.cd = 90;
	treeWizz.hp = 6;
	treeWizz.hptimer = 0;
	treeWizz.width2 = 0;
	treeWizz.height2 = 0;
	treeWizz.deadtrees = 0;
	treeWizz.herp = 0;
	treeWizz.frame = 0;
	treeWizz.pts = 2000;
	treeWizz.spawned = 0;
	treeWizz.index = 1;
	
	TwizEffect.x = 500;
	TwizEffect.y = -400;
	TwizEffect.width = 32;
	TwizEffect.height = 32;
	TwizEffect.onScreen = 0;
	TwizEffect.frame = 0;
	TwizEffect.played = 0;
	
	Thief.type = "Thief";
	Thief.state = 2;
	Thief.spell = "N/A";
	Thief.x = 9000;
	Thief.onTree = 0;
	Thief.y = -400;
	Thief.width = 32;
	Thief.height = 32;
	Thief.speed = 4;
	Thief.speed2 = 2;
	Thief.dirct = 0;
	Thief.dir = "W";
	Thief.respawn = 10;
	Thief.rp = 450;
	Thief.onScreen = 0;
	Thief.counter = 0;
	Thief.runCounter = -1;
	Thief.movement = false;
	Thief.stole = false;
	Thief.hp = 2;
	Thief.alphaChange = false;
	Thief.hptimer = 0;
	Thief.pts = 250;
	
	ThiefA.type = "Thief";
	ThiefA.state = 2;
	ThiefA.spell = "N/A";
	ThiefA.x = 9000;
	ThiefA.onTree = 0;
	ThiefA.y = -400;
	ThiefA.width = 32;
	ThiefA.height = 32;
	ThiefA.speed = 4;
	ThiefA.speed2 = 2;
	ThiefA.dirct = 0;
	ThiefA.dir = "W";
	ThiefA.respawn = 600;
	ThiefA.rp = 450;
	ThiefA.onScreen = 0;
	ThiefA.counter = 0;
	ThiefA.runCounter = -1;
	ThiefA.movement = false;
	ThiefA.stole = false;
	ThiefA.hp = 2;
	ThiefA.alphaChange = false;
	ThiefA.hptimer = 0;
	ThiefA.pts = 250;
	//Deprecated Thief
	ThiefB.type = "Thief";
	ThiefB.state = 2;
	ThiefB.spell = "N/A";
	ThiefB.x = 9000;
	ThiefB.onTree = 0;
	ThiefB.y = -400;
	ThiefB.width = 32;
	ThiefB.height = 32;
	ThiefB.speed = 4;
	ThiefB.speed2 = 2;
	ThiefB.dirct = 0;
	ThiefB.dir = "W";
	ThiefB.respawn = -1;
	ThiefB.rp = -1;
	ThiefB.onScreen = 0;
	ThiefB.counter = 0;
	ThiefB.alphaChange = false;
	ThiefB.runCounter = -1;
	ThiefB.movement = false;
	ThiefB.stole = false;
	ThiefB.hp = 2;
	ThiefB.hptimer = 0;
	ThiefB.pts = 250;
	
	Dragon.type = "Dragon";
	Dragon.x = 9000;
	Dragon.onTree = 0;
	Dragon.y = -400;
	Dragon.width = 268;
	Dragon.height = 218;
	Dragon.speed = 4;
	Dragon.speed2 = 2;
	Dragon.dirct = 0;
	Dragon.dir = "D";
	Dragon.respawn = 2000;
	Dragon.rp = -1;
	Dragon.onScreen = 0;
	Dragon.movement = false;
	Dragon.cd = 90;
	Dragon.hp = 6;
	Dragon.hptimer = 0;
	Dragon.width2 = 0;
	Dragon.height2 = 0;
	Dragon.frame = 0;
	Dragon.pts = 1000;
	Dragon.spawned = 0;
	
	DragonR.type = "DragonR";
	DragonR.x = 9000;
	DragonR.onTree = 0;
	DragonR.y = -400;
	DragonR.width = 42;
	DragonR.height = 64;
	DragonR.speed = 4;
	DragonR.speed2 = 2;
	DragonR.dirct = 0;
	DragonR.dir = "D";
	DragonR.respawn = -1;
	DragonR.origrp = -1;
	DragonR.rp = -1;
	DragonR.onScreen = 0;
	DragonR.movement = false;
	DragonR.cd = 90;
	DragonR.hp = 3;
	DragonR.hptimer = 0;
	DragonR.spawned = 0;
	DragonR.pts = 500;
	
	DragonL.type = "DragonL";
	DragonL.x = 9000;
	DragonL.onTree = 0;
	DragonL.y = -400;
	DragonL.width = 42;
	DragonL.height = 64;
	DragonL.speed = 4;
	DragonL.speed2 = 2;
	DragonL.dirct = 0;
	DragonL.dir = "D";
	DragonL.respawn = -1;
	DragonL.origrp = -1;
	DragonL.rp = -1;
	DragonL.onScreen = 0;
	DragonL.movement = false;
	DragonL.cd = 90;
	DragonL.hp = 3;
	DragonL.hptimer = 0;
	DragonL.width2 = 0;
	DragonL.height2 = 0;
	DragonL.pts = 500;
	DragonL.spawned = 0;
	
	DragonEffect.x = 500;
	DragonEffect.y = -400;
	DragonEffect.width = 288;
	DragonEffect.height = 288;
	DragonEffect.frame = 0;
	DragonEffect.cd = 90;
	
	DragonEffect2.x = 500;
	DragonEffect2.y = -400;
	DragonEffect2.width = 32;
	DragonEffect2.height = 32;
	DragonEffect2.onScreen = 0;
	DragonEffect2.frame = 0;
	DragonEffect2.played = 0;
	//------------------------ EnemyAttacks.js ------------------//
	Globblyfire.color = "#FF6600";
	Globblyfire.x = -100;
	Globblyfire.y = -200;
	Globblyfire.timeLeft = 0;
	Globblyfire.width = 16;
	Globblyfire.height = 16;
	Globblyfire.frame = 0;
	Globblyfire.onScreen = 0;
	
	Globblyfire2.color = "#FF6600";
	Globblyfire2.x = -100;
	Globblyfire2.y = -200;
	Globblyfire2.timeLeft = 0;
	Globblyfire2.width = 16;
	Globblyfire2.height = 16;
	Globblyfire2.frame = 0;
	Globblyfire2.onScreen = 0;
	
	Globblyfire3.color = "#FF6600";
	Globblyfire3.x = -100;
	Globblyfire3.y = -200;
	Globblyfire3.timeLeft = 0;
	Globblyfire3.width = 16;
	Globblyfire3.height = 16;
	Globblyfire3.frame = 0;
	Globblyfire3.onScreen = 0;
	
	for(E in EMplosions){
		EMplosions[E].color = "#FF6600";
		EMplosions[E].x = -100;
		EMplosions[E].y = -200;
		EMplosions[E].timeLeft = 0;
		EMplosions[E].width = 16;
		EMplosions[E].height = 16;
		EMplosions[E].frame = 0;
		EMplosions[E].onScreen = 0;
	}
	
	sIce.color = "#00CCFF";
	sIce.timeLeft = 0;
	sIce.width = 32;
	sIce.height = 32;
	sIce.x = -100;
	sIce.y = -200;
	sIce.frame = 0;
	sIce.onScreen = 0;
	sIce.end = false;
	
	sFire.color = "#FF6600";
	sFire.timeLeft = 0;
	sFire.width = 32;
	sFire.height = 32;
	sFire.x = -100;
	sFire.y = -200;
	sFire.frame = 0;
	sFire.onScreen = 0;
	
	sLightning.timeLeft = 0;
	sLightning.vwidth = 32;
	sLightning.vheight = 800;
	sLightning.hwidth = 800;
	sLightning.hheight = 32;
	sLightning.hstate = 0;
	sLightning.vstate = 0;
	sLightning.hx = 400;
	sLightning.hy = -2000;
	sLightning.vx = -2000;
	sLightning.vy = 288;
	sLightning.onScreen = 0;
	
	rootBlastW.color = "#33CC00";
	rootBlastW.x = -100;
	rootBlastW.y = -200;
	rootBlastW.ox = -100;
	rootBlastW.oy = -200;
	rootBlastW.width = 32;
	rootBlastW.height = 8;
	rootBlastW.hwidth = 8;
	rootBlastW.hheight = 32;
	rootBlastW.frame = 0;
	rootBlastW.cd = 0;
	rootBlastW.speed = 16;
	rootBlastW.onScreen = 0;
	rootBlastW.dir = "W";
	
	rootBlastA.color = "#33CC00";
	rootBlastA.x = -100;
	rootBlastA.y = -200;
	rootBlastA.ox = -100;
	rootBlastA.oy = -200;
	rootBlastA.width = 32;
	rootBlastA.height = 8;
	rootBlastA.hwidth = 8;
	rootBlastA.hheight = 32;
	rootBlastA.frame = 0;
	rootBlastA.cd = 0;
	rootBlastA.speed = 16;
	rootBlastA.onScreen = 0;
	rootBlastA.dir = "A";
	
	rootBlastS.color = "#33CC00";
	rootBlastS.x = -100;
	rootBlastS.y = -200;
	rootBlastS.ox = -100;
	rootBlastS.oy = -200;
	rootBlastS.width = 32;
	rootBlastS.height = 8;
	rootBlastS.hwidth = 8;
	rootBlastS.hheight = 32;
	rootBlastS.frame = 0;
	rootBlastS.cd = 0;
	rootBlastS.speed = 16;
	rootBlastS.onScreen = 0;
	rootBlastS.dir = "S";
	
	rootBlastD.color = "#33CC00";
	rootBlastD.x = -100;
	rootBlastD.y = -200;
	rootBlastD.ox = -100;
	rootBlastD.oy = -200;
	rootBlastD.width = 32;
	rootBlastD.height = 8;
	rootBlastD.hwidth = 8;
	rootBlastD.hheight = 32;
	rootBlastD.frame = 0;
	rootBlastD.cd = 0;
	rootBlastD.speed = 16;
	rootBlastD.onScreen = 0;
	rootBlastD.dir = "D";
	
	for(R in roots1){
		roots1[R].x = -500;
		roots1[R].y = -500;
		roots1[R].width = 16;
		roots1[R].height = 16;
		roots1[R].onScreen = 0;
	}
	
	rootStrike.type = -2;
	rootStrike.x = -500;
	rootStrike.y = -500;
	rootStrike.onTree = 0;
	rootStrike.width = 16;
	rootStrike.height = 16;
	rootStrike.dirct = 0;
	rootStrike.speed = 8;
	rootStrike.speed2 = 4;
	rootStrike.respawn = -1;
	rootStrike.origrp = -1;
	rootStrike.pts = 25;
	rootStrike.hp = 2;
	rootStrike.hptimer = 0;
	rootStrike.dir = "W";
	rootStrike.rp = -1;
	rootStrike.index = 0;
	rootStrike.frame = 0;
	rootStrike.onScreen = 0;
	rootStrike.movement = false;
	
	rootStrike2.type = -3;
	rootStrike2.x = -500;
	rootStrike2.y = -500;
	rootStrike2.onTree = 0;
	rootStrike2.width = 16;
	rootStrike2.height = 16;
	rootStrike2.dirct = 0;
	rootStrike2.speed = 8;
	rootStrike2.speed2 = 4;
	rootStrike2.respawn = -1;
	rootStrike2.origrp = -1;
	rootStrike2.pts = 25;
	rootStrike2.hp = 2;
	rootStrike2.hptimer = 0;
	rootStrike2.dir = "W";
	rootStrike2.rp = -1;
	rootStrike2.index = 0;
	rootStrike2.frame = 0;
	rootStrike2.onScreen = 0;
	rootStrike2.movement = false;
	
	rootStrike3.type = -4;
	rootStrike3.x = -500;
	rootStrike3.y = -500;
	rootStrike3.onTree = 0;
	rootStrike3.width = 16;
	rootStrike3.height = 16;
	rootStrike3.dirct = 0;
	rootStrike3.speed = 8;
	rootStrike3.speed2 = 4;
	rootStrike3.respawn = -1;
	rootStrike3.origrp = -1;
	rootStrike3.pts = 25;
	rootStrike3.hp = 2;
	rootStrike3.hptimer = 0;
	rootStrike3.dir = "W";
	rootStrike3.rp = -1;
	rootStrike3.index = 0;
	rootStrike3.frame = 0;
	rootStrike3.onScreen = 0;
	rootStrike3.movement = false;
	
	rootStrike4.type = -5;
	rootStrike4.x = -500;
	rootStrike4.y = -500;
	rootStrike4.width = 16;
	rootStrike4.onTree = 0;
	rootStrike4.height = 16;
	rootStrike4.dirct = 0;
	rootStrike4.speed = 8;
	rootStrike4.speed2 = 4;
	rootStrike4.respawn = -1;
	rootStrike4.origrp = -1;
	rootStrike4.pts = 25;
	rootStrike4.hp = 2;
	rootStrike4.hptimer = 0;
	rootStrike4.dir = "W";
	rootStrike4.rp = -1;
	rootStrike4.index = 0;
	rootStrike4.frame = 0;
	rootStrike4.onScreen = 0;
	rootStrike4.movement = false;
	
	LeafHeal.color = "#33CC00";
	LeafHeal.timeLeft = 0;
	LeafHeal.x = -100;
	LeafHeal.y = -200;
	LeafHeal.speed = 4;
	LeafHeal.cast = 0;
	LeafHeal.used = 0;
	
	SmokeBomb.color = "black";
	SmokeBomb.width = 32;
	SmokeBomb.height = 32;
	SmokeBomb.x1 = 0;
	SmokeBomb.y1 = 0;
	SmokeBomb.onScreen = 0;
	SmokeBomb.draaw = 0;
	SmokeBomb.frame = 0;
	SmokeBomb.used = 0;
	
	SmokeBombA.color = "black";
	SmokeBombA.width = 32;
	SmokeBombA.height = 32;
	SmokeBombA.x1 = 0;
	SmokeBombA.y1 = 0;
	SmokeBombA.onScreen = 0;
	SmokeBombA.draaw = 0;
	SmokeBombA.frame = 0;
	SmokeBombA.used = 0;
	
	SmokeBombB.color = "black";
	SmokeBombB.width = 32;
	SmokeBombB.height = 32;
	SmokeBombB.x1 = 0;
	SmokeBombB.y1 = 0;
	SmokeBombB.onScreen = 0;
	SmokeBombB.draaw = 0;
	SmokeBombB.frame = 0;
	SmokeBombB.used = 0;
	
	DragonFire.cd = 0;
	for(D in Dragonflame){
		Dragonflame[D].color1 = "#FF6600";
		Dragonflame[D].color2 = "#990000";
		Dragonflame[D].color3 = "#FFCC00";
		Dragonflame[D].x = -100;
		Dragonflame[D].y = -200;
		Dragonflame[D].width = 32;
		Dragonflame[D].height = 8;
		Dragonflame[D].dir = "D";
		Dragonflame[D].frame = 0;
		Dragonflame[D].speed = 16;
		Dragonflame[D].onScreen = 0;
	}
	
	BigMeteor1.type = "Meteor";
	BigMeteor1.x = -9000;
	BigMeteor1.y = -2000;
	BigMeteor1.timeLeft = 0;
	BigMeteor1.num = 1;
	BigMeteor1.onTree = 0;
	BigMeteor1.speed = 8;
	BigMeteor1.speed2 = 4;
	BigMeteor1.immunity = 0;
	BigMeteor1.width = 32;
	BigMeteor1.height = 32;
	BigMeteor1.movement = false;
	BigMeteor1.respawn = -1;
	BigMeteor1.rs = -1;
	BigMeteor1.dir = "D";
	
	Meteor1.type = "Meteor";
	Meteor1.x = -9000;
	Meteor1.y = -2000;
	Meteor1.timeLeft = 0;
	Meteor1.onTree = 0;
	Meteor1.speed = 8;
	Meteor1.speed2 = 4;
	Meteor1.immunity = 0;
	Meteor1.width = 16;
	Meteor1.height = 16;
	Meteor1.movement = false;
	Meteor1.respawn = -1;
	Meteor1.rs = -1;
	Meteor1.dir = "SD";
	
	Meteor2.type = "Meteor";
	Meteor2.x = -9000;
	Meteor2.y = -2000;
	Meteor2.timeLeft = 0;
	Meteor2.onTree = 0;
	Meteor2.speed = 8;
	Meteor2.speed2 = 4;
	Meteor2.immunity = 0;
	Meteor2.width = 16;
	Meteor2.height = 16;
	Meteor2.movement = false;
	Meteor2.respawn = -1;
	Meteor2.rs = -1;
	Meteor2.dir = "WD";
	
	Meteor3.type = "Meteor";
	Meteor3.x = -9000;
	Meteor3.y = -2000;
	Meteor3.timeLeft = 0;
	Meteor3.onTree = 0;
	Meteor3.speed = 8;
	Meteor3.speed2 = 4;
	Meteor3.immunity = 0;
	Meteor3.width = 16;
	Meteor3.height = 16;
	Meteor3.movement = false;
	Meteor3.respawn = -1;
	Meteor3.rs = -1;
	Meteor3.dir = "D2D";
	
	Meteor4.type = "Meteor";
	Meteor4.x = -9000;
	Meteor4.y = -2000;
	Meteor4.timeLeft = 0;
	Meteor4.onTree = 0;
	Meteor4.speed = 8;
	Meteor4.speed2 = 4;
	Meteor4.immunity = 0;
	Meteor4.width = 16;
	Meteor4.height = 16;
	Meteor4.movement = false;
	Meteor4.respawn = -1;
	Meteor4.rs = -1;
	Meteor4.dir = "DWD";
	
	BigMeteor2.type = "Meteor";
	BigMeteor2.x = -9000;
	BigMeteor2.y = -2000;
	BigMeteor2.timeLeft = 0;
	BigMeteor2.num = 2;
	BigMeteor2.onTree = 0;
	BigMeteor2.speed = 8;
	BigMeteor2.speed2 = 4;
	BigMeteor2.immunity = 0;
	BigMeteor2.width = 32;
	BigMeteor2.height = 32;
	BigMeteor2.movement = false;
	BigMeteor2.respawn = -1;
	BigMeteor2.rs = -1;
	BigMeteor2.dir = "D";
	
	Meteor5.type = "Meteor";
	Meteor5.x = -9000;
	Meteor5.y = -2000;
	Meteor5.timeLeft = 0;
	Meteor5.onTree = 0;
	Meteor5.speed = 8;
	Meteor5.speed2 = 4;
	Meteor5.immunity = 0;
	Meteor5.width = 16;
	Meteor5.height = 16;
	Meteor5.movement = false;
	Meteor5.respawn = -1;
	Meteor5.rs = -1;
	Meteor5.dir = "SD";
	
	Meteor6.type = "Meteor";
	Meteor6.x = -9000;
	Meteor6.y = -2000;
	Meteor6.timeLeft = 0;
	Meteor6.onTree = 0;
	Meteor6.speed = 8;
	Meteor6.speed2 = 4;
	Meteor6.immunity = 0;
	Meteor6.width = 16;
	Meteor6.height = 16;
	Meteor6.movement = false;
	Meteor6.respawn = -1;
	Meteor6.rs = -1;
	Meteor6.dir = "WD";
	
	Meteor7.type = "Meteor";
	Meteor7.x = -9000;
	Meteor7.y = -2000;
	Meteor7.timeLeft = 0;
	Meteor7.onTree = 0;
	Meteor7.speed = 8;
	Meteor7.speed2 = 4;
	Meteor7.immunity = 0;
	Meteor7.width = 16;
	Meteor7.height = 16;
	Meteor7.movement = false;
	Meteor7.respawn = -1;
	Meteor7.rs = -1;
	Meteor7.dir = "D2D";
	
	Meteor8.type = "Meteor";
	Meteor8.x = -9000;
	Meteor8.y = -2000;
	Meteor8.timeLeft = 0;
	Meteor8.onTree = 0;
	Meteor8.speed = 8;
	Meteor8.speed2 = 4;
	Meteor8.immunity = 0;
	Meteor8.width = 16;
	Meteor8.height = 16;
	Meteor8.movement = false;
	Meteor8.respawn = -1;
	Meteor8.rs = -1;
	Meteor8.dir = "DWD";
	
	MeteorD1.type = "Meteor";
	MeteorD1.x = -9000;
	MeteorD1.y = -2000;
	MeteorD1.timeLeft = 0;
	MeteorD1.onTree = 0;
	MeteorD1.speed = 8;
	MeteorD1.speed2 = 4;
	MeteorD1.immunity = 0;
	MeteorD1.width = 16;
	MeteorD1.height = 16;
	MeteorD1.movement = false;
	MeteorD1.respawn = -1;
	MeteorD1.rs = -1;
	MeteorD1.dir = "D";
	
	MeteorD2.type = "Meteor";
	MeteorD2.x = -9000;
	MeteorD2.y = -2000;
	MeteorD2.timeLeft = 0;
	MeteorD2.onTree = 0;
	MeteorD2.speed = 8;
	MeteorD2.speed2 = 4;
	MeteorD2.immunity = 0;
	MeteorD2.width = 16;
	MeteorD2.height = 16;
	MeteorD2.movement = false;
	MeteorD2.respawn = -1;
	MeteorD2.rs = -1;
	MeteorD2.dir = "D";
	
	EMeteor1.type = "Meteor";
	EMeteor1.x = 64;
	EMeteor1.y = 256;
	EMeteor1.timeLeft = -1;
	EMeteor1.speed = 4;
	EMeteor1.width = 32;
	EMeteor1.height = 32;
	EMeteor1.respawn = -1;
	EMeteor1.dir = "D";
	
	EMeteor2.type = "Meteor";
	EMeteor2.x = -50;
	EMeteor2.y = 400;
	EMeteor2.timeLeft = -1;
	EMeteor2.speed = 4;
	EMeteor2.width = 32;
	EMeteor2.height = 32;
	EMeteor2.respawn = -1;
	EMeteor2.dir = "DWD";
	
	EMeteor3.type = "Meteor";
	EMeteor3.x = 0;
	EMeteor3.y = -32;
	EMeteor3.timeLeft = -1;
	EMeteor3.speed = 4;
	EMeteor3.width = 32;
	EMeteor3.height = 32;
	EMeteor3.respawn = -1;
	EMeteor3.dir = "D2D";
	
	EMeteor4.type = "Meteor";
	EMeteor4.x = 0;
	EMeteor4.y = 576;
	EMeteor4.timeLeft = -1;
	EMeteor4.speed = 4;
	EMeteor4.width = 16;
	EMeteor4.height = 16;
	EMeteor4.respawn = -1;
	EMeteor4.dir = "DWD";
	
	EMeteor5.type = "Meteor";
	EMeteor5.x = 0;
	EMeteor5.y = 64;
	EMeteor5.timeLeft = -1;
	EMeteor5.speed = 4;
	EMeteor5.width = 16;
	EMeteor5.height = 16;
	EMeteor5.respawn = -1;
	EMeteor5.dir = "D";
	
	EMeteor6.type = "Meteor";
	EMeteor6.x = -32;
	EMeteor6.y = 128;
	EMeteor6.timeLeft = -1;
	EMeteor6.speed = 4;
	EMeteor6.width = 16;
	EMeteor6.height = 16;
	EMeteor6.respawn = -1;
	EMeteor6.dir = "D2D";
	
	EMeteor7.type = "Meteor";
	EMeteor7.x = 0;
	EMeteor7.y = 376;
	EMeteor7.timeLeft = -1;
	EMeteor7.speed = 4;
	EMeteor7.width = 16;
	EMeteor7.height = 16;
	EMeteor7.respawn = -1;
	EMeteor7.dir = "WD";
	
	EMeteor8.type = "Meteor";
	EMeteor8.x = 0;
	EMeteor8.y = 64;
	EMeteor8.timeLeft = -1;
	EMeteor8.speed = 4;
	EMeteor8.width = 16;
	EMeteor8.height = 16;
	EMeteor8.respawn = -1;
	EMeteor8.dir = "D";
	
	EMeteor9.type = "Meteor";
	EMeteor9.x = 0;
	EMeteor9.y = 420;
	EMeteor9.timeLeft = -1;
	EMeteor9.speed = 4;
	EMeteor9.width = 16;
	EMeteor9.height = 16;
	EMeteor9.respawn = -1;
	EMeteor9.dir = "D2D";
	
	EMeteor10.type = "Meteor";
	EMeteor10.x = 0;
	EMeteor10.y = 128;
	EMeteor10.timeLeft = -1;
	EMeteor10.speed = 4;
	EMeteor10.width = 16;
	EMeteor10.height = 16;
	EMeteor10.respawn = -1;
	EMeteor10.dir = "WD";
	
	EMeteor11.type = "Meteor";
	EMeteor11.x = -64;
	EMeteor11.y = 256;
	EMeteor11.timeLeft = -1;
	EMeteor11.speed = 6;
	EMeteor11.width = 16;
	EMeteor11.height = 16;
	EMeteor11.respawn = -1;
	EMeteor11.dir = "D";
	
	EMeteor12.type = "Meteor";
	EMeteor12.x = 0;
	EMeteor12.y = 576;
	EMeteor12.timeLeft = -1;
	EMeteor12.speed = 6;
	EMeteor12.width = 32;
	EMeteor12.height = 32;
	EMeteor12.respawn = -1;
	EMeteor12.dir = "WD";
	
	EMeteor13.type = "Meteor";
	EMeteor13.x = 0;
	EMeteor13.y = 64;
	EMeteor13.timeLeft = -1;
	EMeteor13.speed = 4;
	EMeteor13.width = 32;
	EMeteor13.height = 32;
	EMeteor13.respawn = -1;
	EMeteor13.dir = "SD";
	
	EMeteor14.type = "Meteor";
	EMeteor14.x = 0;
	EMeteor14.y = 320;
	EMeteor14.timeLeft = -1;
	EMeteor14.speed = 6;
	EMeteor14.width = 32;
	EMeteor14.height = 32;
	EMeteor14.respawn = -1;
	EMeteor14.dir = "D";
	
	EMeteor15.type = "Meteor";
	EMeteor15.x = -128;
	EMeteor15.y = 640;
	EMeteor15.timeLeft = -1;
	EMeteor15.speed = 6;
	EMeteor15.width = 32;
	EMeteor15.height = 32;
	EMeteor15.respawn = -1;
	EMeteor15.dir = "DWD";
	
	EMeteor16.type = "Meteor";
	EMeteor16.x = -128;
	EMeteor16.y = -128;
	EMeteor16.timeLeft = -1;
	EMeteor16.speed = 6;
	EMeteor16.width = 32;
	EMeteor16.height = 32;
	EMeteor16.respawn = -1;
	EMeteor16.dir = "D2D";
	//------------------------ Weapons.js -----------------------//
	for(B in Bullets){
		Bullets[B].x = -100;
		Bullets[B].y = -200;
		Bullets[B].timeLeft = 0;
		Bullets[B].speed = 16;
	}
	mystIndex = 1;
	
	fireice.color1 = "#FF6600";
	fireice.color2 = "#00CCFF";
	fireice.color = "#FF6600";
	fireice.state = 0;
	fireice.x = -1000;
	fireice.y = -200;
	fireice.width = 32;
	fireice.height = 32;
	fireice.frame = 0;
	fireice.cd = 0;
	fireice.onScreen = 0;
	fireice.dir = "W";
	fireice.speed = 16;
	fireice.flicker = 600;
	
	fireheal.cd = 0;
	
	iceheal.cd = 0;
	
	lightningheal.cd = 0;
	
	firelightning.timeLeft = 0;
	firelightning.vwidth = 32;
	firelightning.vheight = 800;
	firelightning.hwidth = 800;
	firelightning.hheight = 32;
	firelightning.hstate = 0;
	firelightning.vstate = 0;
	firelightning.hx = 400;
	firelightning.hy = -2000;
	firelightning.vx = -2000;
	firelightning.vy = 288;
	firelightning.cd = 0;
	firelightning.onScreen = 0;
	firelightning.cast = 0;
	firelightning.used = 0;
	for(F in fireLightnings){
		fireLightnings[F].color = "#FF6600";
		fireLightnings[F].x = -1000;
		fireLightnings[F].y = -200;
		fireLightnings[F].timeLeft = 0;
		fireLightnings[F].width = 32;
		fireLightnings[F].height = 32;
		fireLightnings[F].frame = 0;
		fireLightnings[F].onScreen = 0;
	}
	
	for(H in webhoril){
		webhoril[H].color = "#00CCFF";
		webhoril[H].timeLeft = 0;
		webhoril[H].width = 16;
		webhoril[H].height = 16;
		webhoril[H].x = -2000;
		webhoril[H].y = -2000;
		webhoril[H].frame = 0;
		webhoril[H].onScreen = 0;
		webhoril[H].split = 0;
	}
	for(H in webvertil){
		webvertil[H].color = "#00CCFF";
		webvertil[H].timeLeft = 0;
		webvertil[H].width = 16;
		webvertil[H].height = 16;
		webvertil[H].x = -2000;
		webvertil[H].y = -2000;
		webvertil[H].frame = 0;
		webvertil[H].onScreen = 0;
		webvertil[H].split = 0;
	}
	icelightning.color = "#00CCFF";
	icelightning.cd = 0;
	icelightning.timeLeft = 0;
	icelightning.end = false;
	icelightning.AllEnemiesil = {1: Enemy, 2: EnemyA, 3: EnemyB, 4: EnemyC, 5: Tenemy, 6: TenemyA, 7: TenemyB, 8: Sorceror, 9: Lavaman, 10: Lavaman2, 11: Lavaman3, 12: Lavaman4, 13: Spawner, 14: treeWizz, 15: Thief, 16: ThiefA, 17: ThiefB};
	
	airfire.color1 = "#FF6600";
	airfire.color2 = "#990000";
	airfire.x = -100;
	airfire.y = -200;
	airfire.ox = -100;
	airfire.oy = -200;
	airfire.width = 32;
	airfire.height = 8;
	airfire.frame = 0;
	airfire.cd = 0;
	airfire.speed = 16;
	airfire.onScreen = 0;
	
	airfire12.color1 = "#FF6600";
	airfire12.color2 = "#990000";
	airfire12.x = -100;
	airfire12.y = -200;
	airfire12.width = 32;
	airfire12.height = 8;
	airfire12.frame = 0;
	airfire12.speed = 16;
	airfire12.onScreen = 0;
	
	airfire13.color1 = "#FF6600";
	airfire13.color2 = "#990000";
	airfire13.x = -100;
	airfire13.y = -200;
	airfire13.width = 32;
	airfire13.height = 8;
	airfire13.frame = 0;
	airfire13.speed = 16;
	airfire13.onScreen = 0;
	
	airice.color1 = "#3300CC";
	airice.color2 = "#33CCCC";
	airice.x = -100;
	airice.y = -200;
	airice.timeLeft = 0;
	airice.width = 64;
	airice.height = 64;
	airice.cd = 0;
	airice.onScreen = 0;
	airice.cast = 0;
	airice.used = 0;
	
	airearth.cd = 0;
	
	airlightning.timeLeft = 0;
	airlightning.vwidth = 32;
	airlightning.vheight = 800;
	airlightning.hwidth = 800;
	airlightning.hheight = 32;
	airlightning.hx = 400;
	airlightning.hy = -2000;
	airlightning.vx = -2000;
	airlightning.vy = 288;
	airlightning.cd = 0;
	airlightning.onScreen = 0;
	airlightning.LonScreen = 0;
	airlightning.frame = 0;
	
	mysticearth.cd = 0;
	
	waterfire.x = -100;
	waterfire.y = -200;
	waterfire.width = 16;
	waterfire.height = 16;
	waterfire.timeLeft = 0;
	waterfire.cd = 0;
	waterfire.cd2 = 0;
	waterfire.index = 1;
	waterfire.Iindex = 0;
	waterfire.speed = 12;
	waterfire.onScreen = 0;
	waterfire.used = 0;
	waterfire.played = 0;
	waterfire.dir = "";
	for(W in waterFires){
		waterFires[W].x = -100;
		waterFires[W].y = -200;
		waterFires[W].width = 16;
		waterFires[W].height = 16;
		waterFires[W].speed = 12;
		waterFires[W].index = 1;
		waterFires[W].Iindex = 0;
		waterFires[W].onScreen = 0;
		waterFires[W].used = 0;
		waterFires[W].dir = "";
	}
	for(W in WFires){
		WFires[W].color = "#FF6600";
		WFires[W].x = -100;
		WFires[W].y = -200;
		WFires[W].timeLeft = 0;
		WFires[W].width = 32;
		WFires[W].height = 32;
		WFires[W].frame = 0;
		WFires[W].cd = 0;
		WFires[W].onScreen = 0;
		WFires[W].used = 0;
	}
	for(I in IBubbles){
		IBubbles[I].color = "#00CCFF";
		IBubbles[I].timeLeft = 0;
		IBubbles[I].width = 32;
		IBubbles[I].height = 32;
		IBubbles[I].x = -100;
		IBubbles[I].y = -200;
		IBubbles[I].frame = 0;
		IBubbles[I].onScreen = 0;
	}
	
	waterearth.cd = 0;
	
	waterair.x = -100;
	waterair.y = -200;
	waterair.cd = 0;
	waterair.onScreen = 0;
	waterair.frame = 0;
	waterair.mode = 0;
	wairParticleW.x = -100;
	wairParticleW.y = -200;
	wairParticleW.width = 32;
	wairParticleW.height = 32;
	wairParticleW.dir = "W";
	wairParticleW.mdir = "W";
	wairParticleW.speed = 12;
	wairParticleW.dirct = 15;
	wairParticleW.onScreen = 0;
	wairParticleA.x = -100;
	wairParticleA.y = -200;
	wairParticleA.width = 32;
	wairParticleA.height = 32;
	wairParticleA.dir = "A";
	wairParticleA.mdir = "A";
	wairParticleA.speed = 12;
	wairParticleA.dirct = 15;
	wairParticleA.onScreen = 0;
	wairParticleS.type = 0;
	wairParticleS.x = -100;
	wairParticleS.y = -200;
	wairParticleS.width = 32;
	wairParticleS.height = 32;
	wairParticleS.dir = "S";
	wairParticleS.mdir = "S";
	wairParticleS.speed = 12;
	wairParticleS.dirct = 15;
	wairParticleS.onScreen = 0;
	wairParticleD.type = 0;
	wairParticleD.x = -100;
	wairParticleD.y = -200;
	wairParticleD.width = 32;
	wairParticleD.height = 32;
	wairParticleD.dir = "D";
	wairParticleD.mdir = "D";
	wairParticleD.speed = 12;
	wairParticleD.dirct = 15;
	wairParticleD.onScreen = 0;
	wairParticleWA.type = 0;
	wairParticleWA.x = -100;
	wairParticleWA.y = -200;
	wairParticleWA.width = 32;
	wairParticleWA.height = 32;
	wairParticleWA.dir = "WA";
	wairParticleWA.mdir = "WA";
	wairParticleWA.speed = 12;
	wairParticleWA.dirct = 15;
	wairParticleWA.onScreen = 0;
	wairParticleWD.type = 0;
	wairParticleWD.x = -100;
	wairParticleWD.y = -200;
	wairParticleWD.width = 32;
	wairParticleWD.height = 32;
	wairParticleWD.dir = "WD";
	wairParticleWD.mdir = "WD";
	wairParticleWD.speed = 12;
	wairParticleWD.dirct = 15;
	wairParticleWD.onScreen = 0;
	wairParticleAS.type = 0;
	wairParticleAS.x = -100;
	wairParticleAS.y = -200;
	wairParticleAS.width = 32;
	wairParticleAS.height = 32;
	wairParticleAS.dir = "AS";
	wairParticleAS.mdir = "AS";
	wairParticleAS.speed = 12;
	wairParticleAS.dirct = 15;
	wairParticleAS.onScreen = 0;
	wairParticleSD.type = 0;
	wairParticleSD.x = -100;
	wairParticleSD.y = -200;
	wairParticleSD.width = 32;
	wairParticleSD.height = 32;
	wairParticleSD.dir = "SD";
	wairParticleSD.mdir = "SD";
	wairParticleSD.speed = 12;
	wairParticleSD.dirct = 15;
	wairParticleSD.onScreen = 0;
	
	waterlightning.onScreen = 0;
	waterlightning.cd = 0;
	waterlightning.frame = 0;
	for(W in Wpools){
		Wpools[W].color = "#0000FF";
		Wpools[W].color2 = "#FFFF00";
		Wpools[W].timeLeft = 0;
		Wpools[W].width = 32;
		Wpools[W].height = 32;
		Wpools[W].x = -100;
		Wpools[W].y = -200;
		Wpools[W].frame = 0;
		Wpools[W].onScreen = 0;
		Wpools[W].charged = 0;
	}
	//------------------------ Fire.js --------------------------//
	fire.color = "#FF6600";
	fire.x = -100;
	fire.y = -200;
	fire.timeLeft = 0;
	fire.width = 32;
	fire.height = 32;
	fire.frame = 0;
	fire.cd = 0;
	fire.onScreen = 0;
	fire.cast = 0;
	fire.used = 0;
	fire2.color = "#FF6600";
	fire2.x = -1000;
	fire2.y = -200;
	fire2.timeLeft = 0;
	fire2.width = 32;
	fire2.height = 32;
	fire2.frame = 0;
	fire2.cd = 0;
	fire2.onScreen = 0;
	Mfire.color = "#FF6600";
	Mfire.x = -100;
	Mfire.y = -200;
	Mfire.width = 32;
	Mfire.height = 32;
	Mfire.frame = 0;
	Mfire.onScreen = 0;
	Mfire2.color = "#FF6600";
	Mfire2.x = -100;
	Mfire2.y = -200;
	Mfire2.width = 32;
	Mfire2.height = 32;
	Mfire2.frame = 0;
	Mfire2.onScreen = 0;
	Mfire3.color = "#FF6600";
	Mfire3.x = -100;
	Mfire3.y = -200;
	Mfire3.width = 32;
	Mfire3.height = 32;
	Mfire3.frame = 0;
	Mfire3.onScreen = 0;
	Mfire4.color = "#FF6600";
	Mfire4.x = -100;
	Mfire4.y = -200;
	Mfire4.width = 32;
	Mfire4.height = 32;
	Mfire4.frame = 0;
	Mfire4.onScreen = 0;
	//------------------------ Ice.js ---------------------------//
	ice.color = "#00CCFF";
	ice.timeLeft = 0;
	ice.width = 32;
	ice.height = 32;
	ice.x = -100;
	ice.y = -200;
	ice.frame = 0;
	ice.cd = 0;
	ice.onScreen = 0;
	ice.end = false;
	ice.cast = 0;
	ice.used = 0;
	ice2.color = "#00CCFF";
	ice2.timeLeft = 0;
	ice2.width = 32;
	ice2.height = 32;
	ice2.x = -100;
	ice2.y = -200;
	ice2.frame = 0;
	ice2.cd = 0;
	ice2.onScreen = 0;
	ice2.end = false;
	Mice.color = "#00CCFF";
	Mice.timeLeft = 0;
	Mice.width = 32;
	Mice.height = 32;
	Mice.x = -100;
	Mice.y = -200;
	Mice.frame = 0;
	Mice.onScreen = 0;
	Mice2.color = "#00CCFF";
	Mice2.timeLeft = 0;
	Mice2.width = 32;
	Mice2.height = 32;
	Mice2.x = -100;
	Mice2.y = -200;
	Mice2.frame = 0;
	Mice2.onScreen = 0;
	Mice3.color = "#00CCFF";
	Mice3.timeLeft = 0;
	Mice3.width = 32;
	Mice3.height = 32;
	Mice3.x = -100;
	Mice3.y = -200;
	Mice3.frame = 0;
	Mice3.onScreen = 0;
	Mice4.color = "#00CCFF";
	Mice4.timeLeft = 0;
	Mice4.width = 32;
	Mice4.height = 32;
	Mice4.x = -100;
	Mice4.y = -200;
	Mice4.frame = 0;
	Mice4.onScreen = 0;
	//------------------------ Earth.js -------------------------//
	earth.color = "#33CC00";
	earth.timeLeft = 0;
	earth.x = -100;
	earth.y = -200;
	earth.cd = 0;
	earth.speed = 4;
	earth.cast = 0;
	earth.used = 0;
	earth2.color = "#33CC00";
	earth2.timeLeft = 0;
	earth2.x = -100;
	earth2.y = -200;
	earth2.cd = 0;
	earth2.speed = 4;
	earth2.cast = 0;
	earth2.used = 0;
	//------------------------ Lightning.js ---------------------//
	lightning.timeLeft = 0;
	lightning.vwidth = 32;
	lightning.vheight = 800;
	lightning.hwidth = 800;
	lightning.hheight = 32;
	lightning.hx = 400;
	lightning.hy = -2000;
	lightning.vx = -2000;
	lightning.vy = 288;
	lightning.hstate = 0;
	lightning.vstate = 0;
	lightning.cd = 0;
	lightning.onScreen = 0;
	lightning.cast = 0;
	lightning.used = 0;
	lightning12.timeLeft = 0;
	lightning12.vwidth = 32;
	lightning12.vheight = 800;
	lightning12.hwidth = 800;
	lightning12.hheight = 32;
	lightning12.hstate = 0;
	lightning12.vstate = 0;
	lightning12.hx = 400;
	lightning12.hy = -2000;
	lightning12.vx = -2000;
	lightning12.vy = 288;
	lightning12.onScreen = 0;
	lightning2.timeLeft = 0;
	lightning2.vwidth = 32;
	lightning2.vheight = 800;
	lightning2.hwidth = 800;
	lightning2.hheight = 32;
	lightning2.hstate = 0;
	lightning2.vstate = 0;
	lightning2.hx = 400;
	lightning2.hy = -2000;
	lightning2.vx = -2000;
	lightning2.vy = 288;
	lightning2.cd = 0;
	lightning2.onScreen = 0;
	lightning22.timeLeft = 0;
	lightning22.vwidth = 32;
	lightning22.vheight = 800;
	lightning22.hwidth = 800;
	lightning22.hheight = 32;
	lightning22.hstate = 0;
	lightning22.vstate = 0;
	lightning22.hx = 400;
	lightning22.hy = -2000;
	lightning22.vx = -2000;
	lightning22.vy = 288;
	lightning22.onScreen = 0;
	lightning23.timeLeft = 0;
	lightning23.vwidth = 32;
	lightning23.vheight = 800;
	lightning23.hwidth = 800;
	lightning23.hheight = 32;
	lightning23.htime = 0;
	lightning23.hstate = 0;
	lightning23.vstate = 0;
	lightning23.hx = 400;
	lightning23.hy = -2000;
	lightning23.vx = -2000;
	lightning23.vy = 288;
	lightning23.onScreen = 0;
	//------------------------ Air.js ---------------------------//
	air.timeLeft = 0;
	air.cd = 0;
	air.speed = 16;
	air.onScreen = 0;
	air.cast = 0;
	air.used = 0;
	air2.timeLeft = 0;
	air2.cd = 0;
	air2.speed = 16;
	air2.onScreen = 0;
	air2.cast = 0;
	air2.num = 0;
	air2.used = 0;
	//------------------------ Mystic.js ------------------------//
	mystic.color = "#FF00FF";
	mystic.width = 32;
	mystic.height = 32;
	mystic.x = player.x;
	mystic.y = player.y;
	mystic.x1 = 0;
	mystic.y1 = 0;
	mystic.cd = 0;
	mystic.onScreen = 0;
	mystic.cast = 0;
	mystic.mult = 6;
	mystic.mult2 = 0;
	mystic.loop = 0;
	mystic.draaw = 0;
	mystic.frame = 0;
	mystic.cast = 0;
	mystic.used = 0;
	mystic2.color = "#FF00FF";
	mystic2.width = 32;
	mystic2.height = 32;
	mystic2.x = player.x;
	mystic2.y = player.y;
	mystic2.x1 = 0;
	mystic2.y1 = 0;
	mystic2.cd = 0;
	mystic2.onScreen = 0;
	mystic2.cast = 0;
	mystic2.mult = 6;
	mystic2.mult2 = 0;
	mystic2.loop = 0;
	mystic2.draaw = 0;
	mystic2.frame = 0;
	mystic2.cast = 0;
	Illusion.width = 32;
	Illusion.height = 32;
	Illusion.width2 = 32;
	Illusion.height2 = 32;
	Illusion.x = -100;
	Illusion.y = 200;
	Illusion.cd = 0;
	Illusion.onScreen = 0;
	Illusion.frame = 0;
	IllusionBlast.color = "FF00FF";
	IllusionBlast.x = -100;
	IllusionBlast.y = -200;
	IllusionBlast.timeLeft = 0;
	IllusionBlast.width = 32;
	IllusionBlast.height = 32;
	IllusionBlast.frame = 0;
	IllusionBlast.onScreen = 0;
	//------------------------ Water.js -------------------------//
	water.timeLeft = 0;
	water.cd = 0;
	water.cast = 0;
	for(B in bubbleRotate){
		bubbleRotate[B].x = -100;
		bubbleRotate[B].y = -200;
		bubbleRotate[B].width = 16;
		bubbleRotate[B].height = 16;
		bubbleRotate[B].speed = 4;
		bubbleRotate[B].onScreen = 0;
		bubbleRotate[B].used = 0;
		bubbleRotate[B].dir = "";
	}

	//end
	if(vol != 1){
		for(S in AllSounds){
			AllSounds[S].currentTime = 0;
			AllSounds[S].pause();
			AllSounds[S].volume = 0.8;
		}
	}
	fastbeepsLow.play();
}